name: Epic
description: A larger initiative broken down into child issues
title: '[EPIC] '
body:
  - type: textarea
    id: why
    attributes:
      label: Why
    validations:
      required: true
  - type: textarea
    id: children
    attributes:
      label: Children
      description: Task list of child issues
      value: |
        - [ ] #
    validations:
      required: true
  - type: textarea
    id: done-when
    attributes:
      label: Done when
    validations:
      required: true
  - type: textarea
    id: what-already-exists
    attributes:
      label: What already exists
    validations:
      required: false
