name: Factory bug
description: Something is broken
body:
  - type: textarea
    id: observed-behavior
    attributes:
      label: Observed behavior
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
    validations:
      required: true
  - type: textarea
    id: relevant-log-excerpt
    attributes:
      label: Relevant log excerpt
      render: text
    validations:
      required: false
